openapi: 3.0.1
info:
  title: API lotto rich for agent operation.
  description: "This is a sample API server of lotto rich"
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  # - url: http://localhost:8080/v2
  #   description: สำหรับ Production server (ไว้ Generate)
  - url: http://localhost:62/v2
    description: สำหรับ Dev server (เครื่องตัวเอง Player)
  # - url: http://128.199.216.219:61/V2/
  #   description: สำหรับ Test play server
  # - url: http://128.199.216.219:62/V2/
  #   description: สำหรับ Test agent server
  # - url: http://128.199.216.219:63/V2/
  #   description: สำหรับ Test owner server
tags:
  - name: agent
paths:
  /agent/login:
    post:
      tags:
        - agent
      summary: Logged in agent user into system.
      operationId: loginAgent
      requestBody:
        description: for agent login
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/agentLoginInput"
        required: true
      responses:
        "200":
          description: successful login
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/login_success_response"
        "400":
          description: Invalid username/password
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/login_fail_response"
      x-swagger-router-controller: agentController
  /agent/logout:
    post:
      tags:
        - agent
      summary: Loggged out current logged in user session.
      operationId: logoutAgent
      requestBody:
        description: token for clear session
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/requestWithToken"
        required: true
      responses:
        "200":
          description: successful logout
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/apiResponse"
      x-swagger-router-controller: agentController
  /agent/paymentRequest:
    post:
      tags:
        - agent
      summary: Agent payment request insert.
      operationId: agentPaymentRequest
      security:
        - bearerAuth: []
      requestBody:
        description: Agent payment request insert data.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/paymentRequestModel"
        required: true
      responses:
        "200":
          description: Insert Complete.
        "405":
          description: Invalid input
          content: {}
      x-swagger-router-controller: agentController
  /agent/paymentRequestList/{agentId}:
    post:
      tags:
        - agent
      summary: List agent payment request list by agent id.
      operationId: listAgentPaymentRequest
      parameters:
        - name: agentId
          in: path
          description: Id of agent.
          required: true
          style: simple
          explode: false
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/paymentRequestListModel"
        "404":
          description: Empty Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/emptyResponse"
      x-swagger-router-controller: agentController
  /agent/paymentDetail/{paymentId}:
    post:
      tags:
        - agent
      summary: Agent payment detail.
      description: Returns a single payment detail by payment id.
      operationId: getPaymentDetailById
      parameters:
        - name: paymentId
          in: path
          description: Id of payment record..
          required: true
          style: simple
          explode: false
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/paymentDetailModel"
        "404":
          description: Id not found
          content: {}
      x-swagger-router-controller: agentController
  /agent/approvePlayerPayment/{paymentId}:
    post:
      tags:
        - agent
      summary: Approve player payment.
      description: Approve player payment by payment id.
      operationId: approvePlayerPayment
      parameters:
        - name: paymentId
          in: path
          description: Id of payment record.
          required: true
          style: simple
          explode: false
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: Approve Complete.
        "404":
          description: Id not found
          content: {}
      x-swagger-router-controller: agentController
  /agent/agentDetail:
    post:
      tags:
        - agent
      summary: Finds agent detail include wallet amount, sum player wallet.
      description: Finds agent detail.
      operationId: findAgentDetail
      security:
        - bearerAuth: []
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/agentDetail"
                x-content-type: application/json
        "400":
          description: Invalid tag value
          content: {}
      x-swagger-router-controller: agentController
  /agent/player/playerRegister:
    post:
      tags:
        - agent
      summary: Agent player register.
      operationId: agentPlayerRegister
      security:
        - bearerAuth: []
      requestBody:
        description: register new player by agent.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/playerModel"
        required: true
      responses:
        "200":
          description: Insert Complete.
        "405":
          description: Invalid input
          content: {}
      x-swagger-router-controller: agentController
  /agent/player/playerList:
    post:
      tags:
        - agent
      summary: List of player.
      operationId: listPlayerByAgentId
      security:
        - bearerAuth: []
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/playerListModel"
        "404":
          description: Empty Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/emptyResponse"
      x-swagger-router-controller: agentController
  /player/paymentRequestList/:
    post:
      tags:
        - agent
      summary: Payment request list of player.
      operationId: listPlayerPaymentRequest
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/listPlayerPaymentRequestBody"
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/paymentRequestListModel"
        "404":
          description: Empty Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/emptyResponse"
      x-swagger-router-controller: agentController
  /player/playerWallet/{playerId}:
    post:
      tags:
        - agent
      summary: Finds player wallet amount by player id.
      description: Finds player wallet.
      operationId: findPlayerWalletById
      parameters:
        - name: playerId
          in: path
          description: Id of agent.
          required: true
          style: simple
          explode: false
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/playerWallet"
                x-content-type: application/json
        "400":
          description: Invalid tag value
          content: {}
      x-swagger-router-controller: agentController
  /player/playerRank/{playerId}:
    post:
      tags:
        - agent
      summary: Finds player rank by player id.
      description: Finds player rank.
      operationId: findPlayerRank
      parameters:
        - name: playerId
          in: path
          description: Id of agent.
          required: true
          style: simple
          explode: false
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/playerRank"
                x-content-type: application/json
        "400":
          description: Invalid tag value
          content: {}
      x-swagger-router-controller: agentController
  /player/playerStatus/{playerId}:
    post:
      tags:
        - agent
      summary: Finds player status by player id.
      description: Finds player status.
      operationId: findPlayerStatus
      parameters:
        - name: playerId
          in: path
          description: Id of agent.
          required: true
          style: simple
          explode: false
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/playerRank"
                x-content-type: application/json
        "400":
          description: Invalid tag value
          content: {}
      x-swagger-router-controller: agentController
  /player/banPlayer/{playerId}:
    post:
      tags:
        - agent
      summary: Ban player.
      description: Ban player.
      operationId: banPlayer.
      parameters:
        - name: playerId
          in: path
          description: Id of agent.
          required: true
          style: simple
          explode: false
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: successful operation
        "400":
          description: Invalid tag value
          content: {}
      x-swagger-router-controller: agentController
  /player/lottoHistory/:
    post:
      tags:
        - agent
      summary: List player lotto history.
      operationId: listPlayerLottoHistory
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/playerLottoHistoryModel"
        "404":
          description: Empty Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/emptyResponse"
      x-swagger-router-controller: agentController
  /agent/employee/employeeRegister:
    post:
      tags:
        - agent
      summary: Agent employee register.
      operationId: agentEmployeeRegister
      security:
        - bearerAuth: []
      requestBody:
        description: register new employee by agent.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/employeeRegisterModel"
        required: true
      responses:
        "200":
          description: Insert Complete.
        "405":
          description: Invalid input
          content: {}
      x-swagger-router-controller: agentController
  /agent/employee/employeeList:
    post:
      tags:
        - agent
      summary: List of employee by agent id.
      operationId: listEmployeeByAgentId
      security:
        - bearerAuth: []
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/employeeListModel"
        "404":
          description: Empty Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/emptyResponse"
      x-swagger-router-controller: agentController
  /employee/employeeDetail/{employeeId}:
    post:
      tags:
        - agent
      summary: Employee detail.
      description: Returns a single employee detail.
      operationId: getEmployeeDetailById
      parameters:
        - name: employeeId
          in: path
          description: Id of employee.
          required: true
          style: simple
          explode: false
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/employeeRegisterModel"
        "404":
          description: Id not found
          content: {}
      x-swagger-router-controller: agentController
  /employee/changeEmployeeStatus/{employeeId}:
    post:
      tags:
        - agent
      summary: Change employee Ban/UnBan.
      description: Ban/Unban.
      operationId: changeEmployeeStatus
      parameters:
        - name: employeeId
          in: path
          description: Id of employee.
          required: true
          style: simple
          explode: false
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: change status successful
        "404":
          description: Id not found
          content: {}
      x-swagger-router-controller: agentController
  /employee/resetPassword/{employeeId}:
    post:
      tags:
        - agent
      summary: Reset employee password..
      description: Get old and new password and check.
      operationId: resetEmployeePassword
      requestBody:
        description: old/new password data.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/resetPasswordModel"
        required: true
      responses:
        "200":
          description: change status successful
      x-swagger-router-controller: agentController
  /employee/employeeLog/{employeeId}:
    post:
      tags:
        - agent
      summary: List of employee log.
      operationId: listEmployeeLog
      parameters:
        - name: employeeId
          in: path
          description: Id of employee.
          required: true
          style: simple
          explode: false
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/employeeLogModel"
        "404":
          description: Empty Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/emptyResponse"
      x-swagger-router-controller: agentController
  /agent/promotion/promotionCreate:
    post:
      tags:
        - agent
      summary: Promotion create by agent.
      operationId: promotionCreate
      security:
        - bearerAuth: []
      requestBody:
        description: create new promotion by agent.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/promotionCreateModel"
        required: true
      responses:
        "200":
          description: Insert Complete.
        "405":
          description: Invalid input
          content: {}
      x-swagger-router-controller: agentController
  /agent/promotion/promotionList:
    post:
      tags:
        - agent
      summary: List of promotion by agent id.
      operationId: listPromotionByAgentId
      security:
        - bearerAuth: []
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/promotionListModel"
        "404":
          description: Empty Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/emptyResponse"
      x-swagger-router-controller: agentController
  /agent/promotion/promotionDetail:
    post:
      tags:
        - agent
      summary: Get promotion detail.
      description: Returns a single promotion detail by promotionId id.
      operationId: getPromotionDetailById
      security:
        - bearerAuth: []
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/promotionDetailModel"
        "404":
          description: Id not found
          content: {}
      x-swagger-router-controller: agentController
  /promotion/promotionUpdate:
    post:
      tags:
        - agent
      summary: Promotion update.
      operationId: promotionUpdate
      requestBody:
        description: update data.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/promotionCreateModel"
        required: true
      responses:
        "200":
          description: Update Complete.
        "405":
          description: Invalid input
          content: {}
      x-swagger-router-controller: agentController
  /agent/register:
    post:
      tags:
        - agent
      summary: Create agent for login test.
      operationId: registerAgent
      requestBody:
        description: Create agent for login test.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/agentRegisterRequest"
        required: true
      responses:
        "200":
          description: Insert Complete.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessResponse"
      x-swagger-router-controller: agentController
components:
  schemas:
    SuccessResponse:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      example:
        code: "LTR-200"
        message: "Success"
    ValidateReponse:
      properties:
        code:
          type: string
        message:
          type: string
      example:
        code: "LTR-405"
        message: "Invalid input"
    ErrorResponse:
      type: object
      properties:
        error:
          $ref: "#/components/schemas/ErrorResponse_error"
    PlayerLoginInput:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
    PlayerPutInput:
      type: object
      properties:
        username:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        password:
          type: string
        phone:
          type: string
        userStatus:
          type: integer
          description: User Status
          format: int32
    playerModel:
      type: object
      properties:
        id:
          type: integer
          format: int64
        playerName:
          type: string
        phoneNumber:
          type: string
        username:
          type: string
        password:
          type: string
        description:
          type: string
        status:
          type: string
      example:
        playerName: "PlayerXXX"
        phoneNumber: "000000000"
        username: "username123"
        password: "123456789"
        description: "This is description."
        status: "active"
    agentRegisterRequest:
      type: object
      properties:
        agentName:
          type: string
        username:
          type: string
        password:
          type: string
        phoneNumber:
          type: string
        email:
          type: string
        description:
          type: string
        agentRefCode:
          type: string
        status:
          type: string
      example:
        {
          agentName: "AgentXX",
          email: "test@test.com",
          phoneNumber: "0000000000",
          username: "AgentXX",
          password: "123456789",
          description: "desc..",
          agentRefCode: "",
          status: "active",
        }
    employeeRegisterModel:
      type: object
      properties:
        title:
          type: string
        firstname:
          type: string
        lastname:
          type: string
        email:
          type: string
        phoneNumber:
          type: string
        username:
          type: string
        password:
          type: string
        description:
          type: string
        workBrginDate:
          type: string
        status:
          type: string
      example:
        {
          title: "นาย",
          firstname: "test",
          lastname: "test",
          email: "test@test.com",
          phoneNumber: "0000000000",
          username: "emp0",
          password: "123456789",
          description: "test",
          workBrginDate: "23-Sep-2021 01:07:15",
          status: "active",
        }
    agentLoginInput:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      example: { username: "AgentXX", password: "123456789" }
    OwnerModel:
      type: object
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        password:
          type: string
        type:
          type: integer
          description: Owner type
          format: int32
    ManagerModel:
      type: object
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        password:
          type: string
        type:
          type: integer
          description: Manager type
          format: int32
    agentDetail:
      type: object
      properties:
        amountCoin:
          type: number
        totalPlayer:
          type: number
        totalPlayerCredit:
          type: number
        totalPromotionnCredit:
          type: number
    playerWallet:
      type: object
      properties:
        amount:
          type: number
    playerRank:
      type: object
      properties:
        rank:
          type: number
    playerStatus:
      type: object
      properties:
        rank:
          type: number
    totalPlayer:
      type: object
      properties:
        amount:
          type: number
      example:
        amount: 250
    totalCredit:
      type: object
      properties:
        amount:
          type: number
      example:
        amount: 150000
    promotionCredit:
      type: object
      properties:
        amount:
          type: number
      example:
        amount: 20000
    paymentRequestModel:
      type: object
      properties:
        paymentType:
          type: string
        wayToPay:
          type: string
        amount:
          type: number
        promotionId:
          type: integer
          format: int64
          nullable: true
      example:
        {
          paymentType: "DP",
          wayToPay: "T",
          paymentAmount: 1000,
          promotionId: 1,
        }
    paymentDetailModel:
      type: object
      properties:
        id:
          type: integer
          format: int64
        paymentType:
          type: string
        wayToPay:
          type: string
        agentId:
          type: integer
          format: int64
        amount:
          type: number
        promotionId:
          type: integer
          format: int64
      example:
        id: 0
        paymentType: "0"
        wayToPay: "2"
        agentId: 6
        amount: 10000
        promotionId: 1
    TransferModel:
      type: object
      properties:
        id:
          type: integer
          format: int64
        userId:
          type: integer
          format: int64
        from:
          type: integer
          format: int64
        to:
          type: integer
          format: int64
        amount:
          type: number
        status:
          type: integer
          format: int64
    apiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    login_success_response:
      type: object
      properties:
        token:
          type: string
      example:
        token: token
    login_fail_response:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
      example: { code: 404, message: "Invalid username/password" }
    ErrorResponse_error:
      type: object
      properties:
        message:
          type: string
        type:
          type: number
    emptyResponse:
      type: object
      example: { data: [], code: "LTR-200", message: "Success" }
    paymentRequestListModel:
      type: object
      properties:
        id:
          type: integer
          format: int64
        type:
          type: string
        wayToPay:
          type: string
        playerName:
          type: string
        promotion:
          type: string
        amount:
          type: number
          format: int64
        status:
          type: string
      example:
        - id: 0
          type: "Deposit"
          wayToPay: "Cash"
          playerName: "PlayerXXX"
          promotion: "Promotion1"
          amount: 100
          status: "0"
        - id: 1
          type: "Deposit"
          wayToPay: "Cash"
          playerName: "PlayerXXX"
          promotion: "Promotion1"
          amount: 100
          status: "0"
    playerListModel:
      type: object
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string
        credit:
          type: integer
          format: int64
        status:
          type: string
      example:
    employeeListModel:
      type: object
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string
        status:
          type: string
      example:
        - id: 0
          username: "PlayerXXX"
          status: "0"
        - id: 1
          username: "PlayerXXX"
          status: "1"
    employeeLogModel:
      type: object
      properties:
        id:
          type: integer
          format: int64
        datetime:
          type: string
        action:
          type: string
      example:
        - id: 0
          datetime: "20-JUN-1990 08:03:00"
          action: "Ban Player 3"
        - id: 1
          datetime: "20-JUN-1990 08:03:00"
          action: "Approve Withdraw Player 1"
    listPlayerPaymentRequestBody:
      type: object
      properties:
        playerId:
          type: integer
          format: int64
        agentId:
          type: integer
          format: int64
      example:
        playerId: 11
        agentId: 1
    playerLottoHistoryModel:
      type: object
      properties:
        id:
          type: integer
          format: int64
        number:
          type: string
        amount:
          type: number
        status:
          type: string
      example:
        - id: 0
          number: "789"
          amount: 50
          status: "0"
        - id: 1
          number: "123"
          amount: 60
          status: "1"
        - id: 2
          number: "555"
          amount: 10
          status: "1"
    resetPasswordModel:
      type: object
      properties:
        oldPassword:
          type: string
        newPassword:
          type: string
      example:
        oldPassword: "123456789"
        newPassword: "987654321"
    promotionCreateModel:
      type: object
      properties:
        promotionName:
          type: string
        promotionType:
          type: string
        rateType:
          type: string
        rateAmount:
          type: number
        dateStart:
          type: string
        dateStop:
          type: string
        description:
          type: string
        status:
          type: string
      example:
        {
          promotionName: "Prmotion 1",
          promotionType: "ฟรีเครดิต",
          rateType: "fixed",
          rateAmount: 500,
          dateStart: "2008-03-09 16:05:07.123",
          dateStop: "2008-4-09 16:05:07.123",
          description: "",
          status: "active",
        }
    promotionListModel:
      type: object
      properties:
        id:
          type: integer
          format: int64
        promotionName:
          type: string
        promotionType:
          type: string
        rateType:
          type: integer
          format: int64
        rateAmount:
          type: number
        dateStart:
          type: string
        dateStop:
          type: string
      example:
        [
          {
            id: 1,
            promotionName: "Promotion 1",
            promotionType: "freeCredit",
            rateType: "fixed",
            rateAmount: 200,
            dateStart: "2021-09-01 13:13:10",
            dateStop: "2021-09-20 13:13:12",
          },
          {
            id: 2,
            promotionName: "Promotion 2",
            promotionType: "newYear",
            rateType: "percent",
            rateAmount: 10,
            dateStart: "2021-09-01 13:13:10",
            dateStop: "2021-09-20 13:13:12",
          },
        ]
    promotionDetailModel:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        type:
          type: integer
          format: int64
        rateType:
          type: integer
          format: int64
        rateAmount:
          type: number
        dateStart:
          type: string
        dateStop:
          type: string
        status:
          type: string
        description:
          type: string
      example:
        id: 0
        name: "Promotion 1"
        type: 1
        rateType: 1
        rateAmount: 10
        dateStart: "2008-03-09 16:05:07.123"
        dateStop: "2008-03-09 16:05:07.123"
        description: "Description"
    requestWithToken:
      type: object
      properties:
        token:
          type: string
      example:
        token: yourExampleToken
  securitySchemes:
    bearerAuth: # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT # optional, arbitrary value for documentation purposes
